[package]
name = "prozessverwaltung"
version = "0.1.0"
edition = "2021"
authors = ["Abdel Malik Najhi"]
license = "GPL-2.0-or-later"


[[bin]]
name = "prozessverwaltung"
path = "src/main.rs"

[dependencies]
chrono = "0.4.26"
