* This is the output of the scheduler simulation.
** About the scheduling processing method
The simulation used the Round Robin (RR) scheduling algorithm.
Switching processes costs 2 time units.
The Round Robin algorithm processes every process up to 7 time units at a time.
** Averages
The average waiting time for the processes is 53.42857.
The average turnaround time for the processes is 88.
The average reaction time for the processes is 10.857142.
** Processes
Process: Prozess1 (ID: 0), Arrival Time: 0, Execution Time: 150, Start: 0, End: 291, Waiting Time: 142, Turnaround Time: 292, Reaction Time 0
Process: Prozess3 (ID: 2), Arrival Time: 2, Execution Time: 22, Start: 9, End: 97, Waiting Time: 74, Turnaround Time: 96, Reaction Time 7
Process: Prozess5 (ID: 4), Arrival Time: 6, Execution Time: 8, Start: 18, End: 45, Waiting Time: 32, Turnaround Time: 40, Reaction Time 12
Process: Prozess7 (ID: 6), Arrival Time: 30, Execution Time: 2, Start: 48, End: 49, Waiting Time: 18, Turnaround Time: 20, Reaction Time 18
Process: Prozess2 (ID: 1), Arrival Time: 55, Execution Time: 7, Start: 70, End: 76, Waiting Time: 15, Turnaround Time: 22, Reaction Time 15
Process: Prozess4 (ID: 3), Arrival Time: 66, Execution Time: 33, Start: 79, End: 158, Waiting Time: 60, Turnaround Time: 93, Reaction Time 13
Process: Prozess6 (ID: 5), Arrival Time: 150, Execution Time: 20, Start: 161, End: 202, Waiting Time: 33, Turnaround Time: 53, Reaction Time 11
