* This is the output of the scheduler simulation.
** About the scheduling processing method
The simulation used the Round Robin (RR) scheduling algorithm.
Switching processes costs 0 time units.
The Round Robin algorithm processes every process up to 3 time units at a time.
** Averages
The average waiting time for the processes is 13.6.
The average turnaround time for the processes is 20.6.
The average reaction time for the processes is 2.2.
** Processes
Process: P1 (ID: 0), Arrival Time: 0, Execution Time: 15, Start: 0, End: 34, Waiting Time: 20, Turnaround Time: 35, Reaction Time 0
Process: P2 (ID: 1), Arrival Time: 0, Execution Time: 7, Start: 3, End: 26, Waiting Time: 20, Turnaround Time: 27, Reaction Time 3
Process: P3 (ID: 2), Arrival Time: 3, Execution Time: 1, Start: 6, End: 6, Waiting Time: 3, Turnaround Time: 4, Reaction Time 3
Process: P4 (ID: 3), Arrival Time: 6, Execution Time: 4, Start: 7, End: 19, Waiting Time: 10, Turnaround Time: 14, Reaction Time 1
Process: P5 (ID: 4), Arrival Time: 6, Execution Time: 8, Start: 10, End: 28, Waiting Time: 15, Turnaround Time: 23, Reaction Time 4
